name = "Moodle"
uuid = "11347627-391a-4e1e-a81e-4020870fc9b5"
authors = [ "Lucas Calixto <lhc.mat@gmail.com>",
            "John W. MacQuarrie <john.macquarrie@gmail.com>",
            "Csaba Schneider <csaba.schneider@gmail.com>"]
version = "0.1.1"


[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LatexPrint = "d2208f48-c256-5759-9089-c25ed2a93924"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
