# This file contains the functions related to questionnaires

# MoodleQuestion is an abstract type defined as the union of all question types
# at the moment only one question type is defined

MoodleQuestion = Union{short_answer_question} 

@doc """ 
The data sructure that holds a questionnaire
"""->

struct moodle_questionnaire
    category::String                    # the category of the questionnaire
    questions::Vector{MoodleQuestion}   # the list of questions
end

@doc """ 
converts a questionnaire to XML string and writes it into a file
""" ->

function MoodleQuestionnaireToXML( questionnaire::moodle_questionnaire,
                                    filename::String )
    # write a header
    str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"*   
            "<!-- This file was generated by a GAP program -->\n\n"*
            "<quiz>\n\n"*
            "<question type=\"category\">\n<category>\n"*
            "<text>\$course\$/top/"*questionnaire.category*"</text>\n"*
            "</category>\n</question>\n\n"

    # write each question
    for q in questionnaire.questions
        str *= QuestionToXML( q )
    end

    # end of questionnaire
    str *= "\n</quiz>\n"

    # write XML into file
    f = open( filename, "w" )
    write( f, str )
    close( f )
    return true
end
