MoodleQuestion = Union{short_answer_question}

struct moodle_questionnaire
    category::String
    questions::Vector{MoodleQuestion}
end

function MoodleQuestionnaireToXML( questoinnaire::moodle_questionnaire,
                                    filename::String )

    str = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"* 
            "<!-- This file was generated by a GAP program -->\n\n"*
            "<quiz>\n\n"*
            "<question type=\"category\">\n<category>\n"*
            "<text>\$course\$/top/"*questoinnaire.category*"</text>\n"*
            "</category>\n</question>\n\n"

    for q in questoinnaire.questions
        str *= QuestionToXML( q )
    end

    str *= "\n</quiz>\n"

    f = open( filename, "w" )
    write( f, str )
    close( f )
    return true
end
